
trigger:
  branches:
    include:
      - dev
  paths:
    exclude:
      - UserApi
      - UserApi.Tests

stages:
  - stage: build
    displayName: Create Artifact
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        continueOnError: false
        steps:
          - task: Docker@2
            displayName: Login to Registry
            inputs:
              command: login
              containerRegistry: MovieAppRegistryConnection

          - task: Docker@2
            displayName: Build Unchecked Docker Image
            inputs:
              command: build
              containerRegistry: MovieAppRegistryConnection
              repository: authapi-unchecked
              tags: $(Build.BuildId)
              Dockerfile: AuthApi/Dockerfile
          
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.6"

          - script: python -m pip install --upgrade pip setuptools wheel
            displayName: "Install Python tools"

          - script: |
              pip install anchorecli
            displayName: Install Anchore CLI tool

          - task: Docker@2
            displayName: Push Unchecked Image
            inputs:
              command: push
              containerRegistry: MovieAppRegistryConnection
              repository: authapi-unchecked
              tags: $(Build.BuildId)

          - task: AnchoreTask@1
            inputs:
              engineUrl: 'http://40.122.117.95:8228/v1'
              engineUser: 'testuser2'
              enginePassword: '$(AnchoreEnginePassword)'
              imageName: 'movieappwmpregistry.azurecr.io/authapi-unchecked:$(Build.BuildId)'
              doVulnScan: true
              minHighAllowed: 0

      - job: verify
        displayName: Verify Artifact
        pool:
          vmImage: 'ubuntu-latest'
        continueOnError: false
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore Dependencies
            inputs:
              command: restore
              restoreDirectory: $(Build.SourcesDirectory)/packages
              projects: "AuthApi/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: Execute Unit Tests
            inputs:
              command: test
              arguments: --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
              workingDirectory: $(Build.SourcesDirectory)/AuthApi.Tests
              restoreDirectory: $(Build.SourcesDirectory)/packages

          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml'

          - task: WhiteSource Bolt@19
            displayName: Whitesource Scan
            inputs:
              cwd: '$(Build.SourcesDirectory)/packages'

  - stage: push
    displayName: Push Final Image
    dependsOn: 'build'
    jobs:
      - job: push
        displayName: Push to Docker Registry
        steps:
          - task: Docker@2
            displayName: Build Final Docker Image
            inputs:
              command: build
              containerRegistry: MovieAppRegistryConnection
              repository: authapi
              tags: $(Build.BuildId)
              Dockerfile: AuthApi/Dockerfile

          - task: Docker@2
            displayName: Push Final Image
            inputs:
              command: push
              containerRegistry: MovieAppRegistryConnection
              repository: authapi
              tags: $(Build.BuildId)

  - stage: publish
    displayName: Publish Artifacts
    dependsOn: 'push'
    jobs:
      - job: publish
        displayName: Publish Infrastructure
        steps:
          - task: PublishBuildArtifacts@1
            displayName: Publish Infrastructure folder
            inputs:
              ArtifactName: Infra
              PathtoPublish: $(Build.SourcesDirectory)/AuthApi/infrastructure

          - task: PublishBuildArtifacts@1
            displayName: Publish Testing Files
            inputs:
              ArtifactName: Tests
              PathtoPublish: $(Build.SourcesDirectory)/AuthApi/testing  

          - task: PublishBuildArtifacts@1
            displayName: Publish Environment Infra
            inputs:
              ArtifactName: EnvInfra
              PathtoPublish: $(Build.SourcesDirectory)/infrastructure/environment

