
trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - AuthApi
      - AuthApi.Tests
    exclude:
      - AuthApi/authapi-buildspec.yml

stages:
  - stage: build
    displayName: Create Artifact
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        continueOnError: false
        steps:
          - task: Docker@2
            displayName: Login to Registry
            inputs:
              command: login
              containerRegistry: MovieAppRegistryConnection

          - task: Docker@2
            displayName: Build Unchecked Docker Image
            inputs:
              command: build
              containerRegistry: MovieAppRegistryConnection
              repository: authapi-unchecked
              tags: $(Build.BuildId)
          
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.6"

          - script: python -m pip install --upgrade pip setuptools wheel
            displayName: "Install Python tools"

          - script: |
              pip install anchorecli
            displayName: Install Anchore CLI tool

          - task: Docker@2
            displayName: Push Unchecked Image
            inputs:
              command: push
              containerRegistry: MovieAppRegistryConnection
              repository: authapi-unchecked
              tags: $(Build.BuildId)

          - task: AnchoreTask@1
            inputs:
              engineUrl: 'http://40.122.117.95:8228/v1'
              engineUser: 'testuser2'
              enginePassword: '$(AnchoreEnginePassword)'
              imageName: 'movieappwmpregistry.azurecr.io/authapi-unchecked:$(Build.BuildId)'
              doVulnScan: true
              minHighAllowed: 0

      - job: verify
        displayName: Verify Artifact
        pool:
          vmImage: 'ubuntu-latest'
        continueOnError: false
        steps:
          - task: DotNetCoreCLI@2
            displayName: Execute Unit Tests
            inputs:
              command: test
              workingDirectory: $(Build.SourcesDirectory)/AuthApi.Tests

          - task: WhiteSource Bolt@19
            inputs:
              cwd: '$(Build.SourcesDirectory)/AuthApi/bin/Debug/netcoreapp2.2/'

  - stage: push
    displayName: Push Artifact
    dependsOn: 'build'
    jobs:
      - job: push
        displayName: Push to Docker Registry
        steps:
          - task: Docker@2
            displayName: Build Final Docker Image
            inputs:
              command: build
              containerRegistry: MovieAppRegistryConnection
              repository: authapi
              tags: $(Build.BuildId)

          - task: Docker@2
            displayName: Push Final Image
            inputs:
              command: push
              containerRegistry: MovieAppRegistryConnection
              repository: authapi
              tags: $(Build.BuildId)

          - task: PublishBuildArtifacts@1
            displayName: Publish CI Infrastructure folder
            inputs:
              ArtifactName: Infra
              PathtoPublish: $(Build.SourcesDirectory)/AuthApi/infrastructure/ci

          - task: PublishBuildArtifacts@1
            displayName: Publish Newman Testing Collection
            inputs:
              ArtifactName: ApiTests
              PathtoPublish: $(Build.SourcesDirectory)/AuthApi/testing  

