trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - UserApi
      - UserApi.Tests
    exclude:
      - UserApi/userapi-buildspec.yml

stages:
  - stage: build
    displayName: Create Artifact
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        continueOnError: false
        steps:
          - task: DotNetCoreCLI@2
            displayName: Publish Service
            inputs:
              command: publish
              arguments: -c Release -o $(Build.SourcesDirectory)/UserApi/output
              workingDirectory: $(Build.SourcesDirectory)/UserApi
              publishWebProjects: false
              zipAfterPublish: false

          - task: ArchiveFiles@2
            displayName: Create Publishable Zip
            inputs:
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/userapi-$(Build.BuildId).zip
              includeRootFolder: false
              rootFolderOrFile: $(Build.SourcesDirectory)/UserApi/output

          - task: CopyFiles@2
            displayName: Copy Infrastructure Scripts
            inputs:
              SourceFolder: $(Build.SourcesDirectory)/UserApi/infrastructure
              TargetFolder: $(Build.ArtifactStagingDirectory)/infra
              CleanTargetFolder: true

          - task: PublishBuildArtifacts@1
            displayName: Publish Artifact
            inputs:
              TargetPath: $(Build.ArtifactStagingDirectory)
